import type { StylePreset } from "./types";

/**
 * Hair style presets.
 *
 * Migrated from hair-twin-mvp/src/constants.ts and restructured to the
 * ai-generation-design §7 style schema (normalized attributes drive the
 * prompt; Korean labels are display-only). The MVP's `normalizedDescription`
 * and consultation copy are preserved; new structured attributes are derived
 * from it so the prompt builder never sees the raw Korean term.
 */
export const STYLE_PRESETS: StylePreset[] = [
  {
    id: "layered-c-curl",
    displayNameKo: "레이어드 C컬",
    category: "perm",
    categoryLabelKo: "컷 + 펌",
    consultationSummaryKo: "얼굴선을 부드럽게 감싸는 중단발/긴머리 레이어와 끝 C컬",
    length: "collarbone to mid-length",
    bangs: "none",
    parting: "natural side part",
    silhouette: "soft face-framing layered silhouette",
    texture: "smooth C-curl ends",
    volume: "moderate natural volume",
    color: { family: "brown", tone: "natural brown", level: 5 },
    defaultMode: "hair_inpaint",
    accent: "#7dd3fc",
    mockProfile: "medium",
  },
  {
    id: "see-through-bob",
    displayNameKo: "시스루뱅 단발",
    category: "cut",
    categoryLabelKo: "컷",
    consultationSummaryKo: "가벼운 앞머리와 턱선 근처의 산뜻한 단발 실루엣",
    length: "chin-length bob",
    bangs: "airy see-through bangs",
    parting: "center part",
    silhouette: "clean rounded bob silhouette",
    texture: "light airy texture",
    volume: "low to moderate volume",
    color: { family: "brown", tone: "soft dark brown", level: 4 },
    defaultMode: "hair_inpaint",
    accent: "#f0abfc",
    mockProfile: "short",
  },
  {
    id: "hush-cut",
    displayNameKo: "허쉬컷",
    category: "cut",
    categoryLabelKo: "컷",
    consultationSummaryKo: "층감과 움직임이 살아있는 가벼운 샤기 레이어",
    length: "medium",
    bangs: "wispy curtain fringe",
    parting: "center part",
    silhouette: "airy shaggy layered silhouette",
    texture: "soft movement around cheekbones and neckline",
    volume: "light airy volume",
    color: { family: "brown", tone: "natural brown", level: 5 },
    defaultMode: "hair_inpaint",
    accent: "#a7f3d0",
    mockProfile: "medium",
  },
  {
    id: "long-wave",
    displayNameKo: "긴 웨이브",
    category: "perm",
    categoryLabelKo: "펌",
    consultationSummaryKo: "긴 기장에 흐르는 듯한 굵은 웨이브와 윤기",
    length: "long",
    bangs: "none",
    parting: "natural side part",
    silhouette: "flowing long silhouette",
    texture: "loose glossy waves",
    volume: "soft blowout volume",
    color: { family: "brown", tone: "warm dark brown", level: 4 },
    defaultMode: "hair_inpaint",
    accent: "#fde68a",
    mockProfile: "long",
  },
  {
    id: "tassel-cut",
    displayNameKo: "태슬컷",
    category: "cut",
    categoryLabelKo: "컷",
    consultationSummaryKo: "끝선이 단정하게 떨어지는 세련된 스트레이트 단발",
    length: "shoulder-length bob",
    bangs: "none",
    parting: "natural side part",
    silhouette: "clean blunt-end silhouette",
    texture: "polished straight texture",
    volume: "sleek low volume",
    color: { family: "brown", tone: "neutral brown", level: 5 },
    defaultMode: "hair_inpaint",
    accent: "#fca5a5",
    mockProfile: "sleek",
  },
  {
    id: "ash-brown-tone-down",
    displayNameKo: "애쉬 브라운 톤다운",
    category: "color",
    categoryLabelKo: "컬러",
    consultationSummaryKo: "붉은기를 낮춘 차분한 애쉬 브라운 컬러",
    length: "unchanged",
    bangs: "unchanged",
    parting: "unchanged",
    silhouette: "unchanged silhouette",
    texture: "unchanged texture",
    volume: "unchanged volume",
    color: { family: "brown", tone: "neutral ash brown, reduced red undertone", level: 6 },
    defaultMode: "color_transfer",
    accent: "#c4b5fd",
    mockProfile: "color",
  },
  {
    id: "balayage",
    displayNameKo: "발레아쥬",
    category: "color",
    categoryLabelKo: "컬러",
    consultationSummaryKo: "자연스럽게 번지는 하이라이트와 입체적인 컬러감",
    length: "unchanged",
    bangs: "unchanged",
    parting: "unchanged",
    silhouette: "unchanged silhouette",
    texture: "unchanged texture",
    volume: "unchanged volume",
    color: { family: "brown", tone: "dimensional balayage highlights", level: 7 },
    defaultMode: "color_transfer",
    accent: "#fdba74",
    mockProfile: "color",
  },
  {
    id: "volume-magic",
    displayNameKo: "볼륨매직",
    category: "perm",
    categoryLabelKo: "펌",
    consultationSummaryKo: "차분한 스트레이트에 뿌리와 끝 볼륨을 살린 스타일",
    length: "medium",
    bangs: "none",
    parting: "natural side part",
    silhouette: "smooth rebonded silhouette",
    texture: "sleek straight with curved ends",
    volume: "natural root lift",
    color: { family: "black", tone: "soft black", level: 2 },
    defaultMode: "hair_inpaint",
    accent: "#99f6e4",
    mockProfile: "sleek",
  },
  {
    id: "leaf-cut",
    displayNameKo: "리프컷",
    category: "cut",
    categoryLabelKo: "컷",
    consultationSummaryKo: "앞머리와 옆머리가 자연스럽게 흐르는 중성적 리프 실루엣",
    length: "medium",
    bangs: "side-swept fringe",
    parting: "natural side part",
    silhouette: "gender-neutral leaf silhouette",
    texture: "soft layers around ears and neckline",
    volume: "moderate volume",
    color: { family: "brown", tone: "natural brown", level: 5 },
    defaultMode: "hair_inpaint",
    accent: "#86efac",
    mockProfile: "medium",
  },
  {
    id: "dandy-cut",
    displayNameKo: "댄디컷",
    category: "cut",
    categoryLabelKo: "컷",
    consultationSummaryKo: "깔끔한 앞머리와 단정한 사이드 라인의 데일리 컷",
    length: "short",
    bangs: "neat fringe",
    parting: "natural side part",
    silhouette: "clean tidy silhouette",
    texture: "refined everyday texture",
    volume: "natural volume",
    color: { family: "black", tone: "soft black", level: 2 },
    defaultMode: "hair_inpaint",
    accent: "#bfdbfe",
    mockProfile: "short",
  },
];

export function getStylePreset(id: string): StylePreset | undefined {
  return STYLE_PRESETS.find((p) => p.id === id);
}
